### ISSUE TITLE
Suggestion regarding positioning

### ISSUE THREAD

**Issue by darkrunedk** [dominikhofacker/audiovisualization#3]
I would suggest, that you make it easier to position the audio visualizer. Right now it hard to change the position of it, primarily due to the javascript/css entanglement.

It would have been nice to have some variables that controlled the positioning. Maybe you could also make a function to fetch the music title, album etc just to untangle it a bit.

**Comment by dominikhofacker** [comment]
Hi! 
Could you be a little but more precise about what you mean by “positioning”? I’m literally about to drop a mobile-ready and responsive update if that’s what you mean. 

And yeah, I definitely agree with you on the 2nd statement. This project is indeed really old, hence some of the coding is either not the best style or slightly confusing, but I’ve kept improving it ever since because it’s one of my most successful projects. I’ll surely work on that when there’s time buddy! 

Best regards,
Dominik

**Comment by darkrunedk** [comment]
Hi.

What I mean about positioning is that it feels like it meant to be centered. What if you wanted it to be in the top right corner or top left corner.

Best regards,
DarkruneDK

**Comment by dominikhofacker** [comment]
Why would you want to do that?
